# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='???', max_length=30, unique=True)),
                ('min_age', models.IntegerField(default=4)),
                ('max_age', models.IntegerField(default=12)),
                ('link_to_app', models.CharField(default='no link', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DesktopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('movies', models.TextField()),
                ('games', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesktopUserManagerLoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('description', models.TextField(default='Email or password is incorrect')),
            ],
        ),
        migrations.CreateModel(
            name='DesktopUserManager',
            fields=[
                ('desktopuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='childrens_desktop.DesktopUser')),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(default='noEmail', max_length=60, unique=True)),
                ('desktop_users', models.TextField()),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('childrens_desktop.desktopuser',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='childrens_desktop.AppModel')),
            ],
            bases=('childrens_desktop.appmodel',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('appmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='childrens_desktop.AppModel')),
                ('category', models.CharField(choices=[('0', 'History'), ('1', 'Drama'), ('2', 'Fantazi'), ('3', 'NoCategory')], default='NoCategory', max_length=1)),
            ],
            bases=('childrens_desktop.appmodel',),
        ),
    ]
