# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrens_desktop', '0002_auto_20160822_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopusermanager',
            name='desktop_users_group',
        ),
        migrations.AddField(
            model_name='desktopuser',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
