# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrens_desktop', '0003_auto_20160824_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopuser',
            name='games',
        ),
        migrations.AddField(
            model_name='desktopuser',
            name='games',
            field=models.ManyToManyField(to='childrens_desktop.Game'),
        ),
        migrations.RemoveField(
            model_name='desktopuser',
            name='movies',
        ),
        migrations.AddField(
            model_name='desktopuser',
            name='movies',
            field=models.ManyToManyField(to='childrens_desktop.Movie'),
        ),
    ]
