# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(null=True)),
                ('category', models.CharField(choices=[('History', 'History'), ('Drama', 'Drama'), ('Fantazi', 'Fantazi'), ('None', 'None')], default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=70)),
                ('person_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
