# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data',
            field=models.TextField(default='[b1, b2]'),
        ),
    ]
